Gpuimplement
kubernetes-sigs/cluster-api-provider-vsphere pull request #1264
Opened 2021-10-05 10:26 UTC by geetikabatra

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

2022-05-09 17:38 UTC, srm09 commented
/retitle ✨GPU and PCI passthrough support

2022-05-09 17:38 UTC, srm09 commented
/assign

2022-06-23 19:48 UTC, srm09 requested changes
few changes needed.

2022-06-23 19:48 UTC, srm09 commented on go.mod
> -	sigs.k8s.io/cluster-api/test v1.1.3
nit: add this back, used by e2e tests

2022-06-23 19:48 UTC, srm09 commented on packaging/flavorgen/flavors/env/envsubts_consts.go
> +	VSpherePCIVendorID           = 4318
Instead of hardcoding these, they need to be added an env variables.

2022-06-23 19:48 UTC, srm09 commented on packaging/flavorgen/flavors/generators.go
> +	deviceID := int32(env.VSpherePCIDeviceID)
I don't think we should add PCI devices as a mandatory thing in our template, we could a new flavor in flavorgen and only add it there.

2022-06-23 19:48 UTC, srm09 commented on pkg/services/govmomi/vcenter/clone.go
> +	}
This is repeated, can be removed

2022-06-23 19:48 UTC, srm09 commented on pkg/services/govmomi/vcenter/clone.go
> +
nit: remove extra line

2022-06-23 19:48 UTC, srm09 commented on pkg/services/govmomi/vcenter/clone.go
> +		}
This can be removed, since they will not be nil after the kubebuilder validation mentioned above.

2022-06-23 19:48 UTC, srm09 commented on pkg/services/govmomi/vcenter/clone.go
> +		}
```suggestion
		allowedDev := types.VirtualPCIPassthroughAllowedDevice{
			VendorId: *pciDevice.VendorID,
			DeviceId: *pciDevice.DeviceID,
		}
```

2022-06-23 19:48 UTC, srm09 commented on pkg/services/govmomi/vcenter/clone.go
> +		deviceKey--
What's this used for?

2022-06-30 05:42 UTC, geetikabatra reviewed
Should we add a comment regarding why we are using a different  **VSphereMachineTemplate** for worker node?

2022-06-30 16:01 UTC, srm09 commented
The `e2e-templates` target now builds a file called `cluster-template-pci.yaml` which has the changes for adding the PCI device array to a separate machine template object. No need to add anything to a the flavorgen code for that.

> Should we add a comment regarding why we are using a different VSphereMachineTemplate for worker node?
Have added a new issue to change our templates to ship a different machine template for the worker nodes. Will finish it today once this PR merges.

/ok-to-test
/remove-lifecycle rotten
/lifecycle active

2022-06-30 18:42 UTC, geetikabatra commented
My E2E tests are looking for a path` {capv}/_artifacts/repository/infrastructure-vsphere/v1.1.1/cluster-template-pci.yaml`
`make e2e` is generates e2e templates first and then proceeds. I can see all the other templates in `{capv}/_artifacts/repository/infrastructure-vsphere/v1.1.1/` Only the pci one is missing. What exactly am I doing wrong here?

```
geetikab-a01:infrastructure-vsphere geetika.b$ cd v1.1.1/
geetikab-a01:v1.1.1 geetika.b$ ls
cluster-template-conformance.yaml	cluster-template-topology.yaml
cluster-template-kcp-remediation.yaml	cluster-template.yaml
cluster-template-md-remediation.yaml	clusterclass-quick-start.yaml
cluster-template-node-drain.yaml	components.yaml
cluster-template-remote-management.yaml	metadata.yaml
```

2022-07-01 15:43 UTC, jayunit100 commented
hi folks, i tested this it seems to work but i had to run `go mod vendor` to compile it using `docker build`

2022-07-01 23:17 UTC, srm09 commented
This test was introduced as part of the PR, possibly could have been flaky.

2022-07-01 23:17 UTC, srm09 commented
/retest

2022-07-05 11:40 UTC, randomvariable commented on apis/v1beta1/types.go
> +	PciDevices []PCIDeviceSpec `json:"pcidevices,omitempty"`
```suggestion
	PciDevices []PCIDeviceSpec `json:"pciDevices,omitempty"`
```

2022-07-05 15:25 UTC, geetikabatra commented
> hi folks, i tested this it seems to work but i had to run `go mod vendor` to compile it using `docker build`

Yep, this is sometimes required.

2022-07-05 19:28 UTC, srm09 commented
/lgtm
/approve

2022-07-05 19:29 UTC, merged

2022-07-12 19:34 UTC, srm09 commented
Docs for the same have been merged in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1571