Allow secrets to be owned by external tools
kubernetes-sigs/cluster-api-provider-vsphere pull request #1428
Opened 2022-02-10 13:34 UTC by farodin91

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Allow secrets to be owned by external tools
```

2022-02-11 07:43 UTC, farodin91 commented
@srm09 I added an issue.

2022-02-11 21:49 UTC, MaxRink commented
#1431 for easier reference :)

2022-02-11 21:50 UTC, MaxRink commented
/ok-to-test i can definitely understand the need

2022-02-15 18:32 UTC, srm09 requested changes
This PR needs to handle the deletion flow for the identity/secret. To be more explicit, checking for ownerRefs and either removing the ownerRef and/or deleting the secret depending on the owners.

2022-02-15 18:32 UTC, srm09 commented
/ok-to-test

2022-02-22 07:59 UTC, farodin91 commented
@srm09 Shouldn't Kubernetes handle ownerRefs correctly? As, it is currently done for just one ownerRef.

2022-02-22 08:00 UTC, farodin91 commented on pkg/identity/identity.go
> +func IsOwnedByIdentityOrCluster(ownerReferences []metav1.OwnerReference) bool {
I added a table test

2022-03-18 16:04 UTC, farodin91 commented
@srm09 Would you like to review it again?

2022-04-25 21:21 UTC, srm09 commented
/retest
/lgtm

2022-04-26 16:45 UTC, srm09 commented
/approve

2022-04-26 21:00 UTC, srm09 commented
/retest

2022-04-26 21:10 UTC, merged