Johananl/ignition
kubernetes-sigs/cluster-api-provider-vsphere pull request #1429
Opened 2022-02-10 17:26 UTC by johananl

**What this PR does / why we need it**:

This PR adds Ignition support to CAPV and implements the first workload cluster flavor which uses Ignition based on Flatcar Container Linux.

Supersedes #1093.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #1006

**Special notes for your reviewer**:

TODO:

- [ ] Add/update e2e tests

**Release note**:

```release-note
Add support for Ignition bootstrap as well as a Flatcar-based cluster flavor.
```

2022-02-10 17:45 UTC, johananl commented
/test pull-cluster-api-provider-vsphere-e2e-all

2022-02-10 19:58 UTC, srm09 commented
I will take sometime to go through the entire PR, but for starters, this will require an explicit E2E test which should be run periodically, and we can talk about to make it PR Blocking or not.

2022-02-11 10:12 UTC, johananl commented
> I will take sometime to go through the entire PR, but for starters, this will require an explicit E2E test which should be run periodically, and we can talk about to make it PR Blocking or not.

Yes, definitely. There is a TODO for adding tests in the description.

2022-02-17 15:56 UTC, johananl commented on test/e2e/data/infrastructure-vsphere/kustomization/ignition/ignition.yaml
> +      template: flatcar-stable-3033.2.2-kube-v1.19.1
TODO: Remove the hardcoding. I need to figure out where to publish the image, which version to use and how to reference it properly in the e2e config.

2022-02-23 09:47 UTC, geetikabatra commented
@johananl Could you also add a readme about how to utilize ignition support.

2022-02-23 09:57 UTC, johananl commented
> @johananl Could you also add a readme about how to utilize ignition support. Reference https://cluster-api.sigs.k8s.io/tasks/experimental-features/ignition.html

Sure. By the way, do we have a docs website for CAPV?

2022-02-23 09:58 UTC, geetikabatra commented
Not yet. I am filing an issue for the same.

2022-02-24 11:25 UTC, johananl commented
/test all

2022-02-24 11:33 UTC, johananl commented
/test all

2022-02-24 13:11 UTC, johananl commented
/test all

2022-02-24 13:34 UTC, johananl commented
/test pull-cluster-api-provider-vsphere-e2e

2022-02-24 13:59 UTC, johananl commented
/retest

2022-02-24 18:49 UTC, johananl commented
/retest

2022-02-24 19:54 UTC, johananl commented
/test pull-cluster-api-provider-vsphere-e2e

2022-03-31 14:33 UTC, johananl commented
Current status: waiting for https://github.com/kubernetes-sigs/image-builder/pull/817 (which is in turn blocked by https://github.com/kubernetes-sigs/image-builder/pull/827) so that we can execute the e2e tests I added which require Flatcar VMs.

2022-09-09 09:53 UTC, johananl commented
@alexander-demichev I assume you're busy and don't want to bug you. For the sake of driving this PR forward, I'm going to rewrite the commit to fix the author problem and put you under `Co-authored-by` in the hopes that doing so would fix the problem. In case you have an up-to-date email for me, please talk to me soon :pray:

2022-09-09 10:10 UTC, johananl commented
Thanks for providing the new address @alexander-demichev. I've amended the commit and CLA looks good now.

2022-09-14 09:53 UTC, johananl commented
/test all

2022-09-14 10:28 UTC, johananl commented
I have the following questions to the maintainers:

1. Do we need a feature gate for Ignition support? Ignition support is [gated](https://github.com/kubernetes-sigs/cluster-api/blob/daab6fdc72704b39e160878acf743c333648ddbb/feature/feature.go#L57) in core CAPI, however in CAPV I don't see any gates implemented at the moment.
2. `pull-cluster-api-provider-vsphere-apidiff-main` is failing because I've modified a couple of function signatures in `pkg/services/govmomi`. This package is an implementation detail AFAICT, so I'm not sure why we need to be backward compatible inside of it. Anyway, in case I'm missing something and we do - what is the process for making the necessary changes there?
3. With Ignition e2e tests now in place, should we make them PR-Blocking? IMO we want to ensure we aren't breaking CAPV for Ignition-powered distros when making changes so I'd say yes, however I wanted to hear your thoughts since doing so will add a bit of CI time.

Thanks!

2022-09-29 09:24 UTC, johananl commented
For the sake of making progress, I'll make some assumptions regarding the answers to my questions above. When we get eyes on this again I'll correct anything I've assumed wrong.

- Reading through other PRs in this repo, it seems the apidiff job isn't required for merging and rather serves as a warning. Let's ignore it then since this PR can't be merged without API changes since we have to start supporting bootstrap format in `pkg/services/govmomi`.
- I'm going to assume we don't need a feature gate.
- I'm going to assume it's a good idea to make the Ignition e2e test PR-blocking to ensure Ignition support doesn't break.

2022-09-29 10:54 UTC, johananl commented
Ready for merging as far as I'm concerned @MaxRink @vrabbi @srm09. I can do a final squash once reviewed.

2022-11-04 13:19 UTC, johananl commented
/test pull-cluster-api-provider-vsphere-test

2022-11-09 12:24 UTC, johananl commented
Ready for merging IMO.

2022-11-10 17:53 UTC, srm09 commented
Could you squash the commits and I will make a final pass at it in the meantime. We can get this merged then. Sorry for the very long wait on this one.

2022-11-11 05:23 UTC, srm09 requested changes
few nits, but overall lgtm. Looking to get this merged once the comments get resolved.

2022-11-11 05:23 UTC, srm09 commented on test/e2e/ignition_test.go
> +	capi_e2e.QuickStartSpec(context.TODO(), func() capi_e2e.QuickStartSpecInput {
```suggestion
	capi_e2e.QuickStartSpec(ctx, func() capi_e2e.QuickStartSpecInput {
```
Use the context that is used in all e2e tests.

2022-11-11 13:19 UTC, johananl commented on packaging/flavorgen/flavors/flavors.go
> +	controlPlane := newIgnitionKubeadmControlplane(444, machineTemplate, files)
Yes, I'm not sure why this parameter is even necessary. I admit I've copy-pasted it from `controlPlane := newKubeadmControlplane(444, cpMachineTemplate, nil)`. Let me remove it.

2022-11-11 13:39 UTC, johananl commented on packaging/flavorgen/flavors/flavors.go
> +	controlPlane := newIgnitionKubeadmControlplane(444, machineTemplate, files)
FWIW I find the "JIT" replacement unexpected and quite confusing, but I guess changing this is out of scope for this PR.

2022-11-11 13:44 UTC, johananl commented on .gitignore
> +test/e2e/data/infrastructure-vsphere/cluster-template-ignition.yaml
Done.

2022-11-11 13:45 UTC, johananl commented on packaging/flavorgen/flavors/flavors.go
> +	controlPlane := newIgnitionKubeadmControlplane(444, machineTemplate, files)
Fixed. I've also removed another occurrence in `newKubeadmControlplane()` in a separate commit.

2022-11-11 14:17 UTC, johananl commented
@srm09 all feedback is handled and the commits are squashed. CI is green except `pull-cluster-api-provider-vsphere-apidiff-main` but IIRC this job is more of an FYI than a blocker (correct?).

Thanks for consistently being a great maintainer! 🙏

2022-11-11 14:21 UTC, johananl commented
Force-pushed again to fix a problem in the test case description.

2022-11-11 16:45 UTC, srm09 commented
/lgtm
/approve

2022-11-11 16:48 UTC, merged