Gc kind
kubernetes-sigs/cluster-api-provider-vsphere pull request #1446
Opened 2022-02-17 12:29 UTC by geetikabatra

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

2022-02-17 17:24 UTC, srm09 commented
As part of this PR, could you also include the other flag mentioned here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1439

2022-02-17 17:30 UTC, srm09 reviewed
one minor nit

2022-02-18 19:40 UTC, srm09 commented
/ok-to-test
/approve

2022-02-22 17:39 UTC, srm09 commented
Could you include the description of the new flag in the https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/test/e2e#running-the-e2e-tests section?

2022-02-24 00:49 UTC, srm09 requested changes
Please address the comments and squash the commits, and this is ready to merge after.

2022-02-24 00:49 UTC, srm09 commented on test/e2e/README.md
> +`SKIP_RESOURCE_CLEANUP`      | This will skip the cleanup of the kind cluster after e2e tests        | `false`
This flags skips cleanup of the resources created during the tests as well as the kind/bootstrap cluster. Could you update the docs to say the same.

2022-02-24 00:49 UTC, srm09 commented on test/e2e/README.md
> +make e2e SKIP_RESOURCE_CLEANUP=false
```suggestion
make e2e
```
Since the flag is set to `false` by default.

2022-02-24 00:49 UTC, srm09 commented on sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha3/zz_generated.conversion.go
> +//go:build !ignore_autogenerated
remove this file, should not be committed.

2022-02-24 00:49 UTC, srm09 commented on sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha4/zz_generated.conversion.go
> +//go:build !ignore_autogenerated
remove this file, should not be committed.

2022-02-25 14:40 UTC, srm09 commented
Do squash the commits before this can be merged.

2022-02-25 14:47 UTC, geetikabatra commented
Done!

2022-02-28 16:45 UTC, srm09 commented
/lgtm

2022-02-28 16:46 UTC, merged