Refactored GetCredentials Method
kubernetes-sigs/cluster-api-provider-vsphere pull request #1451
Opened 2022-02-18 15:06 UTC by VibhorChinda

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # Breaks down the  GetCredentials method into ValidateIdentity, CreateSecretKey, GetKey, GetNamespceKey

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

2022-02-18 15:19 UTC, geetikabatra commented
/ok-to-test

2022-02-18 15:39 UTC, geetikabatra commented
You might want to sign off this PR. 
Do and force push the change: `git commit --amend --signoff`

2022-02-18 16:28 UTC, VibhorChinda commented
> You might want to sign off this PR. Do and force push the change: `git commit --amend --signoff`

@geetikabatra is this alright ?

2022-02-20 14:28 UTC, VibhorChinda commented
@geetikabatra @aartij17 does failing test means the code is breaking somewhere and need to be looked upon ?
Need some feedback and direction on this please.
Thanks :v:

2022-02-21 06:17 UTC, geetikabatra commented
@VibhorChinda Yes, you might want to run `make test` to check if the tests pass in your local.
Also, could you write unit tests for the changes you made above?

2022-02-21 06:20 UTC, geetikabatra requested changes

2022-02-21 06:20 UTC, geetikabatra commented on pkg/identity/identity.go
> +
nit: remove extra line

2022-02-21 06:20 UTC, geetikabatra commented on pkg/identity/identity.go
> +
You can add a unit test for this method in `identity_test.go`

2022-02-21 06:20 UTC, geetikabatra commented on pkg/identity/identity.go
> +
Please add tests for all the above methods.

2022-02-21 07:07 UTC, VibhorChinda commented
> @VibhorChinda Yes, you might want to run `make test` to check if the tests pass in your local. Also, could you write unit tests for the changes you made above?

Ok will do that.
Yes, I will work on creating unit tests now. :v:

2022-02-23 05:16 UTC, VibhorChinda commented
@srm09 will do all the changes being asked.
Just to be sure, only "ValidateInput" method should be created in this PR and test for that should be written right ?

I created all these static methods because the Issue description asked [https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1441] to do so.

2022-02-26 18:37 UTC, VibhorChinda commented
@geetikabatra @srm09 @aartij17 please check :)

2022-03-07 17:18 UTC, aartij17 commented
@VibhorChinda Can you take a look at the failed lint test. You can use `ctx` as the first argument to the function `validateInputs`

2022-03-08 13:26 UTC, VibhorChinda commented
/retest

2022-03-10 17:22 UTC, srm09 commented on pkg/identity/identity_test.go
> +		Expect(k8sclient.Delete(ctx, cluster)).To(Succeed())
Reverse the order, though I think, just deleting the namespace should delete the objects contained in the namespace automaGically.

2022-03-10 17:22 UTC, srm09 commented on pkg/identity/identity_test.go
>  			Expect(err).To(HaveOccurred())
```suggestion
			Expect(validateInputs(nil, cluster)).NotTo(Succeed())
```

2022-03-10 17:22 UTC, srm09 commented on pkg/identity/identity_test.go
> +			err := validateInputs(k8sclient, nil)
Same as above

2022-03-10 17:22 UTC, srm09 commented on pkg/identity/identity_test.go
> +			err := validateInputs(k8sclient, cluster)
Same as above

2022-03-28 21:40 UTC, aartij17 commented
/lgtm

2022-03-29 07:50 UTC, geetikabatra commented
/lgtm

2022-03-29 14:09 UTC, yastij approved these changes
/approve

2022-03-29 17:50 UTC, merged

2022-03-29 17:56 UTC, VibhorChinda commented
First CAPV PR merged 🎉🎉