Add tests for the `services/govmomi/extra` package
kubernetes-sigs/cluster-api-provider-vsphere pull request #1480
Opened 2022-03-16 15:42 UTC by ditsuke

**What this PR does / why we need it**
This PR adds test cases for the public methods under the services/govmomi/extra package. These methods are used to
set cloud init data (used on VM startup) and to set other configuration keys. The new tests cover:
- [x] `config.SetCustomVMXKeys()`
	Passed a string => string map, this method should append all these key, value pairs to the config as `types.OptionValue` structs.
- [x] `config.SetCloudInitUserData()`, `config.SetCloudInitMetadata()`
	Passed byte arrays, these methods are expected to:
	- Store the data in a `guestinfo.userdata`/`guestinfo.metadata` key with a single pass of base64 encoding.
	- Add a key to indicate the encoding format.
	- Ensure the data passed is encoded with exactly a single pass of base64, which includes checking for existing
	  base64 encoding and undoing them before encoding again with 1x base64.

**Which issue(s) this PR fixes**
Fixes #	1471

Signed-off by: ditsuke <ditsuke@protonmail.com>

2022-03-30 15:18 UTC, geetikabatra requested changes

2022-03-30 15:18 UTC, geetikabatra commented on pkg/services/govmomi/extra/extra_suite_test.go
> +		config := getMockConfig()
Same as above.

2022-03-30 15:18 UTC, geetikabatra commented on pkg/services/govmomi/extra/extra_suite_test.go
> +		config := getMockConfig()
Same as above.

2022-03-30 17:02 UTC, ditsuke commented on pkg/services/govmomi/extra/extra_suite_test.go
> +func getMockConfig() *Config {
That looks a lot better! Done with 127ef34

2022-03-30 17:02 UTC, ditsuke commented on pkg/services/govmomi/extra/extra_suite_test.go
> +		for k, v := range customConfigKeys {
Thanks! This felt smelly even when I first wrote it:)

2022-03-30 17:03 UTC, ditsuke commented on pkg/services/govmomi/extra/extra_suite_test.go
> +			Expect(*config).To(ConsistOf(configKeys...))
Couldn't agree more! Done with 127ef34

2022-03-30 17:37 UTC, ditsuke commented
/retest

2022-04-11 23:36 UTC, srm09 commented
/lgtm
/approve

2022-04-11 23:55 UTC, merged