[WIP] 🐛 Delete legacy finalizer, fix setting ownerRef for `VSphereClusterIdentity `
kubernetes-sigs/cluster-api-provider-vsphere pull request #1486
Opened 2022-03-17 23:23 UTC by aartij17

**What this PR does / why we need it**:
This PR does this following - 
- Check if the older VSphereClusterIdentity is present and delete it during the reconcileDelete phase. This is to make sure that clusters upgraded from v1alpha3 to v1alpha4/v1beta1 can be deleted once the finalizers are removed
- Check only the group and kind(and not the version) while setting ownerRef on VSphereClusterIdentity
- Remove explicit secret deletion from VSphereClusterReconciler (this already happens during the delete reconcile loop of VSphereClusterIdentity)

**Which issue(s) this PR fixes**:
Fixes #1482

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

2022-03-17 23:27 UTC, aartij17 commented
/test

2022-03-17 23:27 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-e2e 
/test pull-cluster-api-provider-vsphere-integration-test

2022-03-18 16:23 UTC, srm09 requested changes

2022-03-18 16:23 UTC, srm09 commented on controllers/vspherecluster_reconciler.go
> +const legacyIdentityFinalizer string = "identity/infrastructure.cluster.x-k8s.io"
Do add an explicit comment marking it as Deprecated, kept only for upgrade issues.

2022-03-18 16:23 UTC, srm09 commented on controllers/vspherecluster_reconciler.go
> -				return fmt.Errorf("another cluster has set the OwnerRef for secret: %s/%s", secret.Namespace, secret.Name)
Well I think we need to have the check that this secret is owned by a particular vSphereCluster object only? If this secret owned by another VSphereCluster, then we should throw an error.

2022-03-24 19:13 UTC, aartij17 commented
/test all

2022-03-24 20:07 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-e2e

2022-03-24 20:40 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-verify-lint

2022-03-24 21:59 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-e2e

2022-03-24 23:11 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-e2e

2022-03-24 23:39 UTC, aartij17 commented
/test pull-cluster-api-provider-vsphere-test

2022-03-25 17:33 UTC, aartij17 commented
/test all

2022-03-28 13:58 UTC, yastij reviewed
/approve

2022-03-28 13:58 UTC, yastij commented on controllers/vspherecluster_reconciler.go
> +		if !clusterutilv1.HasOwner(secret.OwnerReferences, clusterv1.GroupVersion.String(),
why do we have this here? Isn't the check above sufficient?

2022-03-28 17:25 UTC, yastij commented
/lgtm

2022-03-28 17:30 UTC, yastij commented
/retest

2022-03-28 17:45 UTC, merged