Update the deprecated vm-operator API to the new repository location
kubernetes-sigs/cluster-api-provider-vsphere pull request #1701
Opened 2022-11-26 12:13 UTC by chiukapoor

Signed-off-by: Chirayu Kapoor <dev.csociety@gmail.com>

**What this PR does / why we need it**:
Update the deprecated vm-operator API to the new repository location

Deprecated: `https://github.com/vmware-tanzu/vm-operator-api`
New: `https://github.com/vmware-tanzu/vm-operator`

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1698

**Special notes for your reviewer**:

None

**Release note**:
```release-note
None
```

2022-11-28 03:27 UTC, srm09 commented
/ok-to-test

2022-11-29 17:53 UTC, srm09 commented
/retest
Was failing due to infra issues which have been resolved now.

2022-11-29 19:17 UTC, srm09 requested changes
Could you revert back the changes made by `make fix`, and squash the changes. As long as `make lint` passes locally, it should pass in the CI as well.
And could you squash the commits as well?

2022-11-30 06:42 UTC, chiukapoor commented
@srm09 `make lint` failed for the below files, so I executed the `make fix` to fix them. The rest of the files were generated during `make test`, so in this squashed commit, I have reverted the `make test` changes.

```
pkg/services/vimmachine.go:454: File is not `gofmt`-ed with `-s` (gofmt)
// with the values from the FailureDomain (if any) set on the owner CAPI machine.
apis/v1beta1/vspheremachine_webhook.go:71: File is not `gofmt`-ed with `-s` (gofmt)
// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type.
apis/v1beta1/vspherevm_webhook.go:77: File is not `gofmt`-ed with `-s` (gofmt)
```

2022-11-30 19:49 UTC, srm09 commented
Could you do this,
- Run `make lint` and makes changes for the ones that are failing. 
- Run `make test` which in turn would run `make generate` which should fix the failing `verify-get` and `verify-crds` jobs listed above.
- Squash all the commits in the branch in a single commit.

That should make this ready to merge.

2022-12-01 07:31 UTC, chiukapoor commented
@srm09 Re-added the `make test` changes, resolved conflicts with `main`, and squashed the commits.

2022-12-01 17:43 UTC, srm09 commented
/lgtm
/approve

2022-12-01 18:43 UTC, merged