allow other identity in vmmachine
kubernetes-sigs/cluster-api-provider-vsphere pull request #1743
Opened 2023-01-17 14:39 UTC by farodin91

**What this PR does / why we need it**:
Allow multiple vcenter in a single cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1720

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

I will try to test it.

**Release note**:

```release-note
Allow custom identity in vmmachine
```

2023-06-05 10:53 UTC, farodin91 commented
We are using this commit to migrate cluster from one vcenter to a different and it works just fine.

2023-06-23 17:15 UTC, farodin91 commented
/remove-lifecycle rotten

2023-06-23 17:16 UTC, farodin91 commented
@MaxRink would you like to look into this PR?

2023-07-05 14:05 UTC, farodin91 commented
@srm09 would you like to look into this PR?

2023-07-20 17:18 UTC, randomvariable commented
We discussed this in the call of 2023/07/23:

* This will need to be marked as a breaking change, as there is a security implication of allowing users to create MachineDeployments targeting differing vcenters.
* We need an expansion of docs about how this works in a cluster and how to set up CPI and CSI in a cluster to  make it work

cc @puneetkatyal

2023-07-28 18:25 UTC, randomvariable requested changes
As per https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1743#issuecomment-1644302112

2023-08-04 08:50 UTC, farodin91 commented
@randomvariable  I started to write a documentation. 

I added a link to external documentation for csi and cpi, do you think this is enough?

How should i mark this a breaking change?

2023-08-04 09:12 UTC, chrischdi commented
/retitle ⚠️ Allow specifying a different credentials per VSphereMachine

(warning because of the security impact)

2023-08-04 12:35 UTC, farodin91 commented
@randomvariable Should i add this to commit message?

2023-09-07 19:02 UTC, guilhermevillote commented
Any updates on this PR? This is something very useful when your infrastructure has multiple vcenters and you constantly needs to migrate machines from one to another..

Thanks

2024-02-07 09:34 UTC, guilhermevillote commented
Hi, any updates on this PR?

2024-02-07 12:22 UTC, chrischdi reviewed
some comments, definetly needs a rebase too.

2024-02-07 12:22 UTC, chrischdi commented on pkg/identity/identity_test.go
> -			Expect(validateInputs(nil, cluster)).NotTo(Succeed())
would need test cases for the new behavior

2024-02-07 12:22 UTC, chrischdi commented on apis/v1alpha3/zz_generated.conversion.go
> +	// WARNING: in.IdentityRef requires manual conversion: does not exist in peer-type
v1alpha3 is gone on main (similar v1alpha4?)

2024-02-07 12:22 UTC, chrischdi commented on docs/multi-vcenter.md
> +In order to run a CAPV cluster in multiple VCenter, you have to configure CPI & CSI to support multi VCenter, see [guide](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmwar
This only links csi, are there also instructions for CPI?

2024-02-07 12:22 UTC, chrischdi commented on pkg/identity/identity.go
> +func GetCredentials(ctx context.Context, c client.Client, cluster *infrav1.VSphereCluster, controllerNamespace string) (*Credentials, error) {
unit tests would be helpful

2024-02-07 12:22 UTC, chrischdi commented on docs/multi-vcenter.md
> +Cluster API Provider vSphere (CAPV) supports multiple VCenter for a single. Therefore CAPV is allowing to define the used identity for each machine. CAPV will check on every Machine first, if there i
Also what does the first sentence mean?

> Cluster API Provider vSphere (CAPV) supports multiple VCenter for a single.

2024-02-07 12:22 UTC, chrischdi commented on docs/multi-vcenter.md
> +# Multi VCenter support
Is most of this better suited to Also should ahve some explanation how it works in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/identity_management.md ?

2024-02-07 12:22 UTC, chrischdi commented on controllers/vspherevm_controller.go
> +		creds, err := identity.GetCredentialsWithExternalIdentity(ctx, r.Client, vsphereCluster, vsphereVM.Spec.IdentityRef, r.Namespace)
Wouldn't this get overwritten below in l 578 when there is a definition on the cluster level already?

2024-03-08 18:44 UTC, guilhermevillote commented
/remove-lifecycle rotten

2024-03-12 09:13 UTC, farodin91 commented
@chrischdi @guilhermevillote If someone like to take over i'm fine. I don't have time at moment to fix it.

2024-03-13 15:46 UTC, chrischdi commented
> @chrischdi @guilhermevillote If someone like to take over i'm fine. I don't have time at moment to fix it.

Thanks @farodin91 !

/help

2024-04-09 12:13 UTC, closed without merging