📖  Add doc detailing node ipam usage
kubernetes-sigs/cluster-api-provider-vsphere pull request #1774
Opened 2023-02-07 22:02 UTC by tylerschultz

**What this PR does / why we need it**:

This PR adds a doc detailing how to use Node IPAM features.

**Release note**:
```release-note
NONE
```

2023-02-13 06:13 UTC, srm09 requested changes
minor nits, thanks for the doc

2023-02-13 06:13 UTC, srm09 commented on docs/node-ipam-demo.md
> +propopsal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md)
```suggestion
InClusterIPAMProvider is the only implementation of the CAPI [Node IPAM
proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220125-ipam-integration.md)
```

2023-02-13 06:13 UTC, srm09 commented on docs/node-ipam-demo.md
> +### install cluster ctl
```suggestion
### install the clusterctl CLI
```

2023-02-13 06:13 UTC, srm09 commented on docs/node-ipam-demo.md
> +Important - The InClusterIPAMProvider does not validate against overlapping
```suggestion
**Important** - The InClusterIPAMProvider does not validate against overlapping
```

2023-02-13 06:13 UTC, srm09 commented on docs/node-ipam-demo.md
> +The generated `cluster.yaml` file contains `VsphereMachineTemplate`
```suggestion
The generated `cluster.yaml` file contains `VSphereMachineTemplate`
```

2023-02-13 06:13 UTC, srm09 commented
/approve

2023-02-15 00:22 UTC, tylerschultz commented
We've resolved the nits, should be good to go. Thanks for the feedback.

2023-02-15 17:08 UTC, srm09 commented
/lgtm
/approve

2023-02-15 17:33 UTC, srm09 commented
/ok-to-test

2023-02-15 17:34 UTC, srm09 commented
@tylerschultz Could you fix the markdown issues??

2023-02-15 18:42 UTC, tylerschultz commented
Markdown now passes lint, sorry bout that.

2023-02-16 17:57 UTC, srm09 commented
/lgtm

2023-02-16 17:57 UTC, merged