📖 provide clarification on the syntax of the ipAddrs field
kubernetes-sigs/cluster-api-provider-vsphere pull request #1828
Opened 2023-03-17 18:28 UTC by rvanderp3

**What this PR does / why we need it**:
When reading the API specs, it was not obvious to me what the syntax of the field was.  This PR updates the description of the `ipAddrs` field to prevent ambiguity when specifying the IP address.

**Which issue(s) this PR fixes**
Resolves a minor issue I found in the [troubleshooting guide](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/troubleshooting.md#a-static-ip-address-must-include-the-segment-length).

**Special notes for your reviewer**:

**Release note**:
None

2023-07-19 10:24 UTC, randomvariable commented
/ok-to-test


Thanks for this, and apologies for the delay.

2023-07-19 10:25 UTC, randomvariable commented
You may need to rebase this on main to pick up all the CI improvements

2023-07-20 17:26 UTC, sbueringer commented
/retitle :book: improve godoc of the ipAddrs field

2023-07-21 04:18 UTC, sbueringer commented on apis/v1beta1/types.go
> +	// to this device.  IP addresses must also specify the segment length in
```suggestion
	// to this device.  IP addresses must also specify the segment length in
```
@rvanderp3 this change in all 3 files should make the linter happy

2023-07-21 04:18 UTC, sbueringer commented on apis/v1beta1/types.go
> +	// to this device.  IP addresses must also specify the segment length in
Maybe also rebase onto main

2023-07-28 18:26 UTC, randomvariable requested changes
As per https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1828#discussion_r1270208576

2023-08-03 17:18 UTC, randomvariable commented
/assign @killianmuldoon

2023-08-04 17:06 UTC, killianmuldoon commented
/close 

In favor of #2168 which makes a minor fix for the linter. Thanks for the contribution @rvanderp3

2023-08-04 17:06 UTC, closed without merging

2023-08-04 17:06 UTC, killianmuldoon reviewed
/close