ServiceAccount Controller: Forcefully set controllere ownership on resourcees being reconciled by CAPV
kubernetes-sigs/cluster-api-provider-vsphere pull request #1926
Opened 2023-05-31 14:32 UTC by randomvariable

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

2023-05-31 14:42 UTC, yastij reviewed
/approve

verify jobs are failing, can you fix them? otherwise lgtm

2023-05-31 14:44 UTC, randomvariable commented
> verify jobs are failing, can you fix them? otherwise lgtm

accidentally deleted the wrong file, lol

2023-05-31 15:12 UTC, randomvariable commented
/retest

2023-05-31 18:21 UTC, srm09 requested changes
Minor nits. Also, it'd be great if you could add an integration test for the same. Thanks :)

2023-05-31 18:21 UTC, srm09 commented on pkg/util/supervisor.go
> +func deleteAllControllers(controlled metav1.Object, ref metav1.OwnerReference) {
```suggestion
func deleteAllControllerRefs(controlled metav1.Object, ref metav1.OwnerReference) {
```

2023-05-31 18:21 UTC, srm09 commented on pkg/util/supervisor.go
> +		if owners[i].Controller != nil && *owners[i].Controller && !referSameObject(owners[i], ref) {
`!referSameObject(owners[i], ref)` is this check for the follow up reconcile loops for the same object? Can you add a comment about the same if that's the case.

2023-06-01 17:42 UTC, srm09 commented
/retitle 🐛 ServiceAccount Controller: Forcefully set controller ownership on resources being reconciled
/lgtm
/approve

2023-06-01 17:43 UTC, merged

2023-06-01 17:53 UTC, randomvariable commented
/cherry-pick release-1.7